/**
 * Writes Firebase messaging service worker assets from repo-root .env (VITE_* / FIREBASE_*).
 * Run via predev / prebuild — keeps public keys out of hand-edited SW files.
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

function loadEnvFile(path) {
  if (!existsSync(path)) return;
  const text = readFileSync(path, "utf8");
  for (const line of text.split("\n")) {
    const t = line.trim();
    if (!t || t.startsWith("#")) continue;
    const eq = t.indexOf("=");
    if (eq < 0) continue;
    const key = t.slice(0, eq).trim();
    let val = t.slice(eq + 1).trim();
    if (
      (val.startsWith('"') && val.endsWith('"')) ||
      (val.startsWith("'") && val.endsWith("'"))
    ) {
      val = val.slice(1, -1);
    }
    if (!(key in process.env)) process.env[key] = val;
  }
}

loadEnvFile(join(root, ".env"));
loadEnvFile(join(root, ".env.local"));
loadEnvFile(join(root, "backend", ".env"));

function env(...keys) {
  for (const k of keys) {
    const v = process.env[k]?.trim();
    if (v) return v;
  }
  return "";
}

const apiKey = env("VITE_FIREBASE_API_KEY", "FIREBASE_WEB_API_KEY");
const projectId = env("VITE_FIREBASE_PROJECT_ID", "FIREBASE_PROJECT_ID");
const messagingSenderId = env("VITE_FIREBASE_MESSAGING_SENDER_ID", "FIREBASE_MESSAGING_SENDER_ID");
const appId = env("VITE_FIREBASE_APP_ID", "FIREBASE_WEB_APP_ID");

if (!apiKey || !projectId || !messagingSenderId || !appId) {
  console.warn(
    "[generate-fcm-sw] Skipped — set VITE_FIREBASE_* (or FIREBASE_WEB_*) in .env to enable web push.",
  );
  process.exit(0);
}

const authDomain =
  env("VITE_FIREBASE_AUTH_DOMAIN", "FIREBASE_AUTH_DOMAIN") || `${projectId}.firebaseapp.com`;
const storageBucket =
  env("VITE_FIREBASE_STORAGE_BUCKET", "FIREBASE_STORAGE_BUCKET") ||
  `${projectId}.appspot.com`;

const firebaseConfig = {
  apiKey,
  authDomain,
  projectId,
  storageBucket,
  messagingSenderId,
  appId,
};

const handlerBody = `
firebase.initializeApp(${JSON.stringify(firebaseConfig)});
const messaging = firebase.messaging();
messaging.onBackgroundMessage(function (payload) {
  if (payload.data && (payload.data.type === "test" || payload.data.event === "test")) return;
  const title =
    (payload.notification && payload.notification.title) ||
    (payload.data && payload.data.title) ||
    "CareTip";
  const body =
    (payload.notification && payload.notification.body) ||
    (payload.data && payload.data.body) ||
    "";
  const tag =
    (payload.data && (payload.data.event || payload.data.type)) || "caretip-notification";
  return self.registration.showNotification(title, {
    body: body,
    icon: "/icon-192.png",
    badge: "/icon-192.png",
    data: payload.data || {},
    tag: tag,
  });
});

self.addEventListener("notificationclick", function (event) {
  event.notification.close();
  var data = event.notification.data || {};
  var target = data.url || "/";
  event.waitUntil(
    clients.matchAll({ type: "window", includeUncontrolled: true }).then(function (list) {
      for (var i = 0; i < list.length; i++) {
        var client = list[i];
        if ("focus" in client) {
          if (target && "navigate" in client) {
            return client.focus().then(function () {
              return client.navigate(target);
            });
          }
          return client.focus();
        }
      }
      if (clients.openWindow) return clients.openWindow(target);
    }),
  );
});
`;

const compatImports = `importScripts("https://www.gstatic.com/firebasejs/11.6.0/firebase-app-compat.js");
importScripts("https://www.gstatic.com/firebasejs/11.6.0/firebase-messaging-compat.js");
`;

const fullSw = `/* Generated by scripts/generate-fcm-sw.mjs — do not edit */
${compatImports}
${handlerBody}`;

const handlerOnly = `/* Generated by scripts/generate-fcm-sw.mjs — imported by Workbox SW */
${handlerBody}`;

writeFileSync(join(root, "public", "firebase-messaging-sw.js"), fullSw, "utf8");
writeFileSync(join(root, "public", "fcm-sw-handler.js"), handlerOnly, "utf8");
console.info("[generate-fcm-sw] Wrote public/firebase-messaging-sw.js and public/fcm-sw-handler.js");
